#:schema https://json.schemastore.org/hugo.json
baseURL = "https://builtindetroit.today/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
images = []
paginate = 1000
theme = "kaigi"
timeZone = "America/Detroit"

[languages]

[languages.en]
contentDir = "content/en"
disabled = false
languageCode = "en-US"
languageDirection = "ltr"
languageName = "English"
title = "Built In Detroit"
weight = 20
[languages.en.params]
description = "Open industrial technology education and engagement. Built in Detroit. By Detroit."
author = "Built In Detroit Project Contributors"

[menu]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10

[params]
github = "BuiltInDetroit"
rss = true

[taxonomies]
bio = "bios"
